config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root :to => 'reminders#index'
  
  resources :reminders
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reminder.rb
# frozen_string_literal: true

class Reminder < ApplicationRecord
  MESSAGE_SUMMARY_LIMIT = 10

  validates :message, presence: true, length: { maximum: 30 }
  validates :datetime, presence: true
  validate  :overdue_datetime?

  def overdue_datetime?
    errors.add(:datetime, "can't be in the past.") if datetime.present? && (datetime < Time.zone.now)
  end

  def date
    datetime.try(:to_date)
  end

  def summary
    return '' if message.blank?

    if message.size > MESSAGE_SUMMARY_LIMIT
      "#{message[0...MESSAGE_SUMMARY_LIMIT]}..."
    else
      message
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def authorize(record, action_name, policy_class); end
end

app/controllers/reminders_controller.rb
# frozen_string_literal: true

class RemindersController < ApplicationController
  def index
    authorize_action
    reminders = Reminder.all
    reminders_by_date = reminders.group_by(&:date)
    render :index, locals: {
      reminders: reminders,
      reminders_by_date: reminders_by_date,
      date: params[:date].present? ? Date.parse(params[:date]) : Time.zone.today
    }
  end

  def new
    authorize_action
    reminder = Reminder.new
    render :new, locals: { reminder: reminder }
  end

  def create
    authorize_action
    reminder = Reminder.create(reminder_params)
    if reminder.save
      redirect_to reminders_path
    else
      render :new, locals: { reminder: reminder }
    end
  end

  def edit
    authorize_action(reminder)
    render :edit, locals: { reminder: reminder }
  end

  def update
    authorize_action(reminder)
    if reminder.update(reminder_params)
      redirect_to reminders_path
    else
      render :edit, locals: { reminder: reminder }
    end
  end

  def destroy
    authorize_action(reminder)
    reminder.destroy!
    redirect_to reminders_path
  end

  private

  def reminder
    @reminder ||= Reminder.find(params[:id])
  end

  def reminder_params
    params.require(:reminder).permit(:message, :datetime, :color)
  end

  def policy_class
    ReminderPolicy
  end

  def authorize_action(record = Reminder)
    authorize(record, "#{action_name}?", policy_class: policy_class)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/calendar_helper.rb
# frozen_string_literal: true

module CalendarHelper
  HEADER = %w[Sun Mon Tue Wed Thu Fri Sat].freeze
  START_DAY = :sunday
  NUMBER_DAY_OF_WEEK = 7

  def calendar(date: Time.zone.today, reminders: [])
    @date = date
    @reminders = reminders
    tag.table(class: 'calendar') do
      header + week_rows
    end
  end

  def header
    tag.thead do
      HEADER.map { |day| tag.th(day) }.join.html_safe
    end
  end

  def week_rows
    weeks.map do |week|
      tag.tr do
        week.map { |day| day_cell(day) }.join.html_safe
      end
    end.join.html_safe
  end

  def day_cell(day)
    tag.td(class: day_classes(day)) do
      concat(tag.span(day.strftime('%e')))
      concat(reminders_by_date(day))
    end
  end

  def day_classes(day)
    classes = []
    classes << 'today' if day == Time.zone.today
    classes << 'sunday' if day.wday.zero?
    classes << 'notmonth' if day.month != @date.month
    classes.empty? ? nil : classes.join(' ')
  end

  def weeks
    first = @date.beginning_of_month.beginning_of_week(START_DAY)
    last = @date.end_of_month.end_of_week(START_DAY)
    (first..last).to_a.in_groups_of(NUMBER_DAY_OF_WEEK)
  end

  def reminders_by_date(day)
    return if @reminders[day].blank?

    tag.ul(class: 'reminder-list') do
      @reminders[day].map do |reminder|
        tag.li(class: 'reminder-item') do
          link_to reminder.summary, edit_reminder_path(reminder), style: "background: #{reminder.color}"
        end
      end.join.html_safe
    end
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    meta charset="utf-8"
    meta content="IE=edge" http-equiv="X-UA-Compatible"
    meta content="width=device-width, initial-scale=1" name="viewport"
    title= t('reminders.title')
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application.css', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_packs_with_chunks_tag 'application', media: 'all'
  body
    = yield

app/views/reminders/_form.html.slim
.form-group
  = f.label :datetime, t('reminders.edit.datetime')
  = f.datetime_field :datetime
.form-group
  = f.label :message, t('reminders.edit.message')
  = f.text_field :message, required: true, maxlength: '30'
.form-group
  = f.label :color, t('reminders.edit.color')
  = f.color_field :color
.form-actions
  = f.submit t('helpers.links.confirm'), :class => 'btn-primary'
  = link_to t('helpers.links.cancel'), reminders_path, :class => 'btn'

app/views/reminders/edit.html.slim
- model_class = Reminder
.page-header
  h1
    = t('reminders.edit.title')
= form_for reminder, :url => reminder_path(reminder), method: :put, :html => { :class => 'form-horizontal' } do |f|
  = render :partial => 'form', :locals => { :f => f }

app/views/reminders/index.html.slim
.main-container
  .reminder-card
    h2.reminder-header
      = link_to t('reminders.index.prev_month'), reminders_path(date: date.prev_month)
      = date.strftime(t('month.formats.default'))
      = link_to t('reminders.index.next_month'), reminders_path(date: date.next_month)
    = calendar(date: date, reminders: reminders_by_date) do |calender_date|
      = calender_date.day
      - if reminders_by_date[calender_date].present?
        ul
          - reminders_by_date[date].each do |reminder|
            li
              = link_to reminder.summary, reminder_path(reminder)
  br
  p
    = link_to t('reminders.index.new'), new_reminder_path, :class => 'btn btn-primary'

app/views/reminders/new.html.slim
- model_class = Reminder
.page-header
  h1
    = t('reminders.create.title')
= form_for reminder, :url => reminders_path, method: :post, :html => { :class => 'form-horizontal' } do |f|
  - if reminder.errors.any?
    p.errors = t('reminders.create.failed')
    ul.errors
      - reminder.errors.full_messages.each do |error|
        li= error
  = render :partial => 'form', :locals => { :f => f }